# Toolscore Full Quality Gates Workflow
# Copy this file to .github/workflows/ in your repository

name: Agent Quality Gates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1: Basic threshold check
  threshold-check:
    runs-on: ubuntu-latest
    name: Threshold Check

    outputs:
      passed: ${{ steps.eval.outputs.passed }}
      selection-accuracy: ${{ steps.eval.outputs.selection-accuracy }}

    steps:
      - uses: actions/checkout@v4

      - name: Evaluate Agent
        uses: yotambraun/toolscore@v1
        id: eval
        with:
          gold-file: tests/gold_standard.json
          trace-file: tests/agent_trace.json
          threshold: '0.85'
          fail-on-regression: 'false'  # Don't fail yet

  # Job 2: Regression check (only if threshold passes)
  regression-check:
    runs-on: ubuntu-latest
    name: Regression Check
    needs: threshold-check
    if: needs.threshold-check.outputs.passed == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Check for Regressions
        uses: yotambraun/toolscore@v1
        id: regression
        with:
          gold-file: tests/gold_standard.json
          trace-file: tests/agent_trace.json
          baseline-file: tests/baseline.json
          regression-threshold: '0.05'
          fail-on-regression: 'true'

  # Job 3: Report summary
  report:
    runs-on: ubuntu-latest
    name: Generate Report
    needs: [threshold-check, regression-check]
    if: always()

    steps:
      - name: Summary
        run: |
          echo "## Quality Gate Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Threshold Check | ${{ needs.threshold-check.outputs.passed == 'true' && '✅ Pass' || '❌ Fail' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Selection Accuracy | ${{ needs.threshold-check.outputs.selection-accuracy }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "*Powered by [Toolscore](https://github.com/yotambraun/toolscore)*" >> $GITHUB_STEP_SUMMARY
